// Auto-generated by scripts/build-photo-manifest.mjs — do not hand-edit.
// Every field here is derived from a real file in public/images/photos/
// (filename, EXIF date/GPS/camera, decoded dimensions) — nothing is invented.
// Re-run the script (see README) after adding or removing source photos.

export const PHOTOS = [
  {
    "id": "img-0827",
    "src": "/images/photos/optimized/img-0827.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-0827.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_0827.HEIC",
    "albumIds": [
      "year-2026"
    ],
    "isFavorite": false,
    "dateTaken": "2026-06-19T18:57:05.000Z",
    "dateLabel": "June 19, 2026",
    "location": {
      "lat": 44.64325,
      "lng": -63.56759,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#4b8acc",
    "tags": [
      "2026"
    ]
  },
  {
    "id": "img-8131",
    "src": "/images/photos/optimized/img-8131.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-8131.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_8131.HEIC",
    "albumIds": [
      "year-2026"
    ],
    "isFavorite": false,
    "dateTaken": "2026-02-07T14:44:47.000Z",
    "dateLabel": "February 7, 2026",
    "location": {
      "lat": 44.63943,
      "lng": -63.58457,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#bed1e1",
    "tags": [
      "2026"
    ]
  },
  {
    "id": "img-9736",
    "src": "/images/photos/optimized/img-9736.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-9736.webp",
    "width": 2400,
    "height": 1800,
    "aspectRatio": 1.3333,
    "filename": "IMG_9736.HEIC",
    "albumIds": [
      "year-2025"
    ],
    "isFavorite": false,
    "dateTaken": "2025-03-10T15:23:48.000Z",
    "dateLabel": "March 10, 2025",
    "location": {
      "lat": 26.92391,
      "lng": 75.82724,
      "label": "Jaipur Municipal Corporation"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#89d2ef",
    "tags": [
      "2025"
    ]
  },
  {
    "id": "img-9649",
    "src": "/images/photos/optimized/img-9649.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-9649.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_9649.HEIC",
    "albumIds": [
      "year-2025"
    ],
    "isFavorite": false,
    "dateTaken": "2025-03-10T13:04:58.000Z",
    "dateLabel": "March 10, 2025",
    "location": {
      "lat": 26.9265,
      "lng": 75.8236,
      "label": "Jaipur Municipal Corporation"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#39333a",
    "tags": [
      "2025"
    ]
  },
  {
    "id": "img-9636",
    "src": "/images/photos/optimized/img-9636.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-9636.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_9636.HEIC",
    "albumIds": [
      "year-2025"
    ],
    "isFavorite": false,
    "dateTaken": "2025-03-10T13:00:04.000Z",
    "dateLabel": "March 10, 2025",
    "location": {
      "lat": 26.92652,
      "lng": 75.82414,
      "label": "Jaipur Municipal Corporation"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#1d3c5f",
    "tags": [
      "2025"
    ]
  },
  {
    "id": "img-9421",
    "src": "/images/photos/optimized/img-9421.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-9421.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_9421.HEIC",
    "albumIds": [
      "year-2025"
    ],
    "isFavorite": false,
    "dateTaken": "2025-03-09T20:19:34.000Z",
    "dateLabel": "March 9, 2025",
    "location": {
      "lat": 26.93803,
      "lng": 75.81544,
      "label": "Jaipur Municipal Corporation"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#57789f",
    "tags": [
      "2025"
    ]
  },
  {
    "id": "img-9390",
    "src": "/images/photos/optimized/img-9390.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-9390.webp",
    "width": 2400,
    "height": 1800,
    "aspectRatio": 1.3333,
    "filename": "IMG_9390.HEIC",
    "albumIds": [
      "year-2025"
    ],
    "isFavorite": false,
    "dateTaken": "2025-03-09T19:15:17.000Z",
    "dateLabel": "March 9, 2025",
    "location": {
      "lat": 26.99138,
      "lng": 75.85126,
      "label": "Jaipur Municipal Corporation"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#8f7d65",
    "tags": [
      "2025"
    ]
  },
  {
    "id": "img-9188",
    "src": "/images/photos/optimized/img-9188.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-9188.webp",
    "width": 2400,
    "height": 1800,
    "aspectRatio": 1.3333,
    "filename": "IMG_9188.HEIC",
    "albumIds": [
      "year-2025"
    ],
    "isFavorite": false,
    "dateTaken": "2025-03-04T22:25:23.000Z",
    "dateLabel": "March 4, 2025",
    "location": {
      "lat": 46.41312,
      "lng": 24.34845,
      "label": "Ogra"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#3c4a56",
    "tags": [
      "2025"
    ]
  },
  {
    "id": "img-9080",
    "src": "/images/photos/optimized/img-9080.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-9080.webp",
    "width": 2400,
    "height": 1800,
    "aspectRatio": 1.3333,
    "filename": "IMG_9080.HEIC",
    "albumIds": [
      "year-2025"
    ],
    "isFavorite": false,
    "dateTaken": "2025-03-01T10:46:13.000Z",
    "dateLabel": "March 1, 2025",
    "location": {
      "lat": 44.62948,
      "lng": -63.57311,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#935b5e",
    "tags": [
      "2025"
    ]
  },
  {
    "id": "img-8928",
    "src": "/images/photos/optimized/img-8928.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-8928.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_8928.HEIC",
    "albumIds": [
      "year-2025"
    ],
    "isFavorite": false,
    "dateTaken": "2025-02-11T21:29:19.000Z",
    "dateLabel": "February 11, 2025",
    "location": {
      "lat": 44.64575,
      "lng": -63.58284,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#8e7b7e",
    "tags": [
      "2025"
    ]
  },
  {
    "id": "img-8788",
    "src": "/images/photos/optimized/img-8788.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-8788.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_8788.HEIC",
    "albumIds": [
      "year-2025"
    ],
    "isFavorite": false,
    "dateTaken": "2025-02-02T21:30:11.000Z",
    "dateLabel": "February 2, 2025",
    "location": {
      "lat": 44.62719,
      "lng": -63.57181,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#2a3e56",
    "tags": [
      "2025"
    ]
  },
  {
    "id": "img-8737",
    "src": "/images/photos/optimized/img-8737.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-8737.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_8737.HEIC",
    "albumIds": [
      "year-2025"
    ],
    "isFavorite": false,
    "dateTaken": "2025-01-31T11:08:24.000Z",
    "dateLabel": "January 31, 2025",
    "location": {
      "lat": 44.62964,
      "lng": -63.57314,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#0c161e",
    "tags": [
      "2025"
    ]
  },
  {
    "id": "img-8702",
    "src": "/images/photos/optimized/img-8702.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-8702.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_8702.HEIC",
    "albumIds": [
      "year-2025"
    ],
    "isFavorite": false,
    "dateTaken": "2025-01-28T21:09:43.000Z",
    "dateLabel": "January 28, 2025",
    "location": {
      "lat": 44.6423,
      "lng": -63.57954,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#3f3f3f",
    "tags": [
      "2025"
    ]
  },
  {
    "id": "img-8689",
    "src": "/images/photos/optimized/img-8689.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-8689.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_8689.HEIC",
    "albumIds": [
      "year-2025"
    ],
    "isFavorite": false,
    "dateTaken": "2025-01-28T20:50:23.000Z",
    "dateLabel": "January 28, 2025",
    "location": {
      "lat": 44.62884,
      "lng": -63.57143,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#6c6d67",
    "tags": [
      "2025"
    ]
  },
  {
    "id": "img-8448",
    "src": "/images/photos/optimized/img-8448.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-8448.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_8448.HEIC",
    "albumIds": [
      "year-2025"
    ],
    "isFavorite": false,
    "dateTaken": "2025-01-10T23:30:05.000Z",
    "dateLabel": "January 10, 2025",
    "location": {
      "lat": 44.62897,
      "lng": -63.57137,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#464443",
    "tags": [
      "2025"
    ]
  },
  {
    "id": "img-7820",
    "src": "/images/photos/optimized/img-7820.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-7820.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_7820.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-11-24T19:59:52.000Z",
    "dateLabel": "November 24, 2024",
    "location": {
      "lat": 44.63814,
      "lng": -63.56916,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#382e1d",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-7711",
    "src": "/images/photos/optimized/img-7711.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-7711.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_7711.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-11-19T22:58:45.000Z",
    "dateLabel": "November 19, 2024",
    "location": {
      "lat": 44.64428,
      "lng": -63.60078,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#100500",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "426c5bf2-da7d-4744-b7e6-85d63689cc6e",
    "src": "/images/photos/optimized/426c5bf2-da7d-4744-b7e6-85d63689cc6e.webp",
    "thumbnailSrc": "/images/photos/thumbs/426c5bf2-da7d-4744-b7e6-85d63689cc6e.webp",
    "width": 1179,
    "height": 2096,
    "aspectRatio": 0.5625,
    "filename": "426C5BF2-DA7D-4744-B7E6-85D63689CC6E.jpg",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-10-26T00:22:12.000Z",
    "dateLabel": "October 25, 2024",
    "location": null,
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#adaca7",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-7070",
    "src": "/images/photos/optimized/img-7070.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-7070.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_7070.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-10-17T19:42:20.000Z",
    "dateLabel": "October 17, 2024",
    "location": {
      "lat": 44.63726,
      "lng": -63.58978,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#3f2814",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-6912",
    "src": "/images/photos/optimized/img-6912.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-6912.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_6912.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-10-11T17:08:45.000Z",
    "dateLabel": "October 11, 2024",
    "location": {
      "lat": 44.64147,
      "lng": -63.56962,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#150700",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-6668",
    "src": "/images/photos/optimized/img-6668.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-6668.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_6668.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-09-20T22:09:33.000Z",
    "dateLabel": "September 20, 2024",
    "location": {
      "lat": 44.61777,
      "lng": -63.56759,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#404f65",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-6605",
    "src": "/images/photos/optimized/img-6605.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-6605.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_6605.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-09-15T12:46:27.000Z",
    "dateLabel": "September 15, 2024",
    "location": {
      "lat": 44.63607,
      "lng": -63.60184,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#254569",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-6405",
    "src": "/images/photos/optimized/img-6405.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-6405.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_6405.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-09-03T18:51:49.000Z",
    "dateLabel": "September 3, 2024",
    "location": {
      "lat": 44.63723,
      "lng": -63.58983,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#341d02",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-6032",
    "src": "/images/photos/optimized/img-6032.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-6032.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_6032.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-08-04T10:08:26.000Z",
    "dateLabel": "August 4, 2024",
    "location": {
      "lat": 44.66427,
      "lng": -63.58401,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#aabdd1",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-5951",
    "src": "/images/photos/optimized/img-5951.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-5951.webp",
    "width": 2400,
    "height": 1800,
    "aspectRatio": 1.3333,
    "filename": "IMG_5951.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-07-28T23:56:21.000Z",
    "dateLabel": "July 28, 2024",
    "location": {
      "lat": 44.62917,
      "lng": -63.57322,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#847882",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-5647",
    "src": "/images/photos/optimized/img-5647.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-5647.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_5647.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-07-07T23:08:33.000Z",
    "dateLabel": "July 7, 2024",
    "location": {
      "lat": 44.64005,
      "lng": -63.58456,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#8599aa",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-5280",
    "src": "/images/photos/optimized/img-5280.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-5280.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_5280.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-06-15T19:12:50.000Z",
    "dateLabel": "June 15, 2024",
    "location": {
      "lat": 44.64269,
      "lng": -63.57844,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#292218",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-5016",
    "src": "/images/photos/optimized/img-5016.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-5016.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_5016.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-06-02T20:02:30.000Z",
    "dateLabel": "June 2, 2024",
    "location": {
      "lat": 44.64316,
      "lng": -63.5676,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#c2d3e3",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-4814",
    "src": "/images/photos/optimized/img-4814.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-4814.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_4814.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-05-22T23:26:45.000Z",
    "dateLabel": "May 22, 2024",
    "location": {
      "lat": 44.66905,
      "lng": -63.57871,
      "label": "Dartmouth"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#bf9d68",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-4487",
    "src": "/images/photos/optimized/img-4487.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-4487.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_4487.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-05-07T09:13:12.000Z",
    "dateLabel": "May 7, 2024",
    "location": {
      "lat": 44.64648,
      "lng": -63.57751,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#a88558",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-4440",
    "src": "/images/photos/optimized/img-4440.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-4440.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_4440.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-05-06T17:59:02.000Z",
    "dateLabel": "May 6, 2024",
    "location": {
      "lat": 44.63674,
      "lng": -63.59161,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#869196",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-3221",
    "src": "/images/photos/optimized/img-3221.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-3221.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_3221.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-02-18T21:41:59.000Z",
    "dateLabel": "February 18, 2024",
    "location": {
      "lat": 44.62946,
      "lng": -63.57337,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#939ab1",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-2206",
    "src": "/images/photos/optimized/img-2206.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-2206.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_2206.HEIC",
    "albumIds": [
      "year-2024"
    ],
    "isFavorite": false,
    "dateTaken": "2024-01-10T02:55:34.000Z",
    "dateLabel": "January 9, 2024",
    "location": {
      "lat": 44.62888,
      "lng": -63.57161,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#d8d8d0",
    "tags": [
      "2024"
    ]
  },
  {
    "id": "img-1668",
    "src": "/images/photos/optimized/img-1668.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-1668.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_1668.HEIC",
    "albumIds": [
      "year-2023"
    ],
    "isFavorite": false,
    "dateTaken": "2023-12-04T20:50:22.000Z",
    "dateLabel": "December 4, 2023",
    "location": {
      "lat": 44.62944,
      "lng": -63.57337,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#718394",
    "tags": [
      "2023"
    ]
  },
  {
    "id": "img-1647",
    "src": "/images/photos/optimized/img-1647.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-1647.webp",
    "width": 2400,
    "height": 1800,
    "aspectRatio": 1.3333,
    "filename": "IMG_1647.HEIC",
    "albumIds": [
      "year-2023"
    ],
    "isFavorite": false,
    "dateTaken": "2023-12-04T11:23:13.000Z",
    "dateLabel": "December 4, 2023",
    "location": {
      "lat": 44.62923,
      "lng": -63.57296,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#88aedb",
    "tags": [
      "2023"
    ]
  },
  {
    "id": "img-0955",
    "src": "/images/photos/optimized/img-0955.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-0955.webp",
    "width": 1800,
    "height": 2400,
    "aspectRatio": 0.75,
    "filename": "IMG_0955.HEIC",
    "albumIds": [
      "year-2023"
    ],
    "isFavorite": false,
    "dateTaken": "2023-11-06T19:32:24.000Z",
    "dateLabel": "November 6, 2023",
    "location": {
      "lat": 44.65067,
      "lng": -63.5708,
      "label": "Halifax"
    },
    "camera": "iPhone 15",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#5189cd",
    "tags": [
      "2023"
    ]
  },
  {
    "id": "img-20230902-213920-original",
    "src": "/images/photos/optimized/img-20230902-213920-original.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-20230902-213920-original.webp",
    "width": 1346,
    "height": 2400,
    "aspectRatio": 0.5608,
    "filename": "IMG_20230902_213920_Original.JPG",
    "albumIds": [
      "year-2023"
    ],
    "isFavorite": false,
    "dateTaken": "2023-09-03T00:39:20.000Z",
    "dateLabel": "September 2, 2023",
    "location": {
      "lat": 44.64134,
      "lng": -63.57649,
      "label": "Halifax"
    },
    "camera": "21091116AI",
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#010302",
    "tags": [
      "2023"
    ]
  },
  {
    "id": "06ff587a-b618-4530-b654-3d2c0a68844d",
    "src": "/images/photos/optimized/06ff587a-b618-4530-b654-3d2c0a68844d.webp",
    "thumbnailSrc": "/images/photos/thumbs/06ff587a-b618-4530-b654-3d2c0a68844d.webp",
    "width": 750,
    "height": 1000,
    "aspectRatio": 0.75,
    "filename": "06FF587A-B618-4530-B654-3D2C0A68844D.jpg",
    "albumIds": [],
    "isFavorite": false,
    "dateTaken": null,
    "dateLabel": null,
    "location": null,
    "camera": null,
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#0f0f12",
    "tags": []
  },
  {
    "id": "78413556-00b2-432f-b7fb-2cb7e7300828",
    "src": "/images/photos/optimized/78413556-00b2-432f-b7fb-2cb7e7300828.webp",
    "thumbnailSrc": "/images/photos/thumbs/78413556-00b2-432f-b7fb-2cb7e7300828.webp",
    "width": 1200,
    "height": 1600,
    "aspectRatio": 0.75,
    "filename": "78413556-00b2-432f-b7fb-2cb7e7300828.jpg",
    "albumIds": [],
    "isFavorite": false,
    "dateTaken": null,
    "dateLabel": null,
    "location": null,
    "camera": null,
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#7f6a5e",
    "tags": []
  },
  {
    "id": "f182643d-f434-4397-a2ff-40455573ca7a",
    "src": "/images/photos/optimized/f182643d-f434-4397-a2ff-40455573ca7a.webp",
    "thumbnailSrc": "/images/photos/thumbs/f182643d-f434-4397-a2ff-40455573ca7a.webp",
    "width": 750,
    "height": 1000,
    "aspectRatio": 0.75,
    "filename": "F182643D-F434-4397-A2FF-40455573CA7A.jpg",
    "albumIds": [],
    "isFavorite": false,
    "dateTaken": null,
    "dateLabel": null,
    "location": null,
    "camera": null,
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#0f0e12",
    "tags": []
  },
  {
    "id": "img-4258",
    "src": "/images/photos/optimized/img-4258.webp",
    "thumbnailSrc": "/images/photos/thumbs/img-4258.webp",
    "width": 1353,
    "height": 2400,
    "aspectRatio": 0.5637,
    "filename": "IMG_4258.JPG",
    "albumIds": [],
    "isFavorite": false,
    "dateTaken": null,
    "dateLabel": null,
    "location": null,
    "camera": null,
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#494256",
    "tags": []
  },
  {
    "id": "snapchat-944618016-original",
    "src": "/images/photos/optimized/snapchat-944618016-original.webp",
    "thumbnailSrc": "/images/photos/thumbs/snapchat-944618016-original.webp",
    "width": 1180,
    "height": 1572,
    "aspectRatio": 0.7506,
    "filename": "Snapchat-944618016_Original.JPG",
    "albumIds": [],
    "isFavorite": false,
    "dateTaken": null,
    "dateLabel": null,
    "location": null,
    "camera": null,
    "alt": "Photograph from Harsh's personal photo library",
    "dominantTone": "#587ec3",
    "tags": []
  }
];
